# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('manageclient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberclient',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.Profile'),
        ),
    ]
