# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageclient', '0002_memberclient_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberclient',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
