# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageclient', '0003_auto_20180721_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberclient',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.Profile'),
        ),
    ]
