# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='memberclient',
            name='member',
        ),
        migrations.DeleteModel(
            name='MemberClient',
        ),
    ]
