# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycleporthole', '0002_auto_20180720_1100'),
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cycles',
        ),
    ]
