# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0003_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycles',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
