# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0004_auto_20180711_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycles',
            old_name='job',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='cycles',
            name='company',
        ),
    ]
