# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0006_auto_20180711_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycles',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
