# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0007_auto_20180712_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycles',
            name='job_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycles',
            name='job_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycles',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
