# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('cycles', '0009_auto_20180715_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycles',
            old_name='job_title',
            new_name='cycle_title',
        ),
        migrations.RemoveField(
            model_name='cycles',
            name='client',
        ),
        migrations.RemoveField(
            model_name='cycles',
            name='location',
        ),
        migrations.AddField(
            model_name='cycles',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Jobs'),
        ),
    ]
