# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managecycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('post_code', models.CharField(max_length=10)),
                ('country', django_countries.fields.CountryField(default='United Kingdom', max_length=2)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('name_on_card', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecycle.Cycles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
