# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20180730_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='PaymentLineItem',
            new_name='OrderLineItem',
        ),
    ]
