# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 15:31
from __future__ import unicode_literals

import cycleporthole.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managecycle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('file', models.FileField(upload_to=cycleporthole.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uploaded_at', models.DateTimeField()),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='InvoiceCycleFK', serialize=False, to='managecycle.Cycles')),
                ('is_invoice', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceUserFK', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceMemberFK', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('file', models.FileField(upload_to=cycleporthole.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uploaded_at', models.DateTimeField()),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='POCycleFK', serialize=False, to='managecycle.Cycles')),
                ('is_po', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='POUserFK', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='POMemberFK', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('file', models.FileField(upload_to=cycleporthole.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uploaded_at', models.DateTimeField()),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='QuotesCycleFK', serialize=False, to='managecycle.Cycles')),
                ('is_quote', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuotesUserFK', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuotesMemberFK', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
