# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycleporthole', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='id',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='id',
        ),
        migrations.AlterField(
            model_name='invoices',
            name='cycle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='InvoiceCycleFK', serialize=False, to='managecycle.Cycles'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='cycle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='POCycleFK', serialize=False, to='managecycle.Cycles'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='cycle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='QuotesCycleFK', serialize=False, to='managecycle.Cycles'),
        ),
    ]
