# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycleporthole', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='is_invoice',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_po',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='is_quote',
        ),
    ]
