# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycleporthole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceCycleFK', to='managecycle.Cycles'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='POCycleFK', to='managecycle.Cycles'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuotesCycleFK', to='managecycle.Cycles'),
        ),
    ]
