# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycleporthole', '0002_auto_20180728_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='is_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_po',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='is_quote',
            field=models.BooleanField(default=True),
        ),
    ]
