# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycleporthole', '0003_auto_20180728_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='cycle_value',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='cycle_value_currency',
        ),
    ]
