# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 18:37
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cycleporthole', '0003_auto_20180714_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='cycle_value',
            field=djmoney.models.fields.MoneyField(decimal_places=1, default=Decimal('0.0'), default_currency='GBP', max_digits=12, validators=[django.core.validators.MinValueValidator(0), djmoney.models.validators.MaxMoneyValidator(10000000000)]),
        ),
    ]
