# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 10:03
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cycleporthole', '0004_auto_20180714_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='cycle_value',
            field=djmoney.models.fields.MoneyField(currency_choices=[('GBP', 'Pound Sterling'), ('EUR', 'Euro')], decimal_places=1, default=Decimal('0'), default_currency='GBP', max_digits=11, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='cycle_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'Pound Sterling'), ('EUR', 'Euro')], default='GBP', editable=False, max_length=3),
        ),
    ]
