# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 16:17
from __future__ import unicode_literals

import cycleporthole.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycleporthole', '0006_auto_20180715_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='is_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_po',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='is_quote',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='file',
            field=models.FileField(upload_to=cycleporthole.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='file',
            field=models.FileField(upload_to=cycleporthole.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='file',
            field=models.FileField(upload_to=cycleporthole.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
