# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managecycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesStatus',
            fields=[
                ('approve', models.BooleanField(default=False)),
                ('contest', models.BooleanField(default=False)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='managecycle.Cycles')),
            ],
        ),
        migrations.CreateModel(
            name='POStatus',
            fields=[
                ('approve', models.BooleanField(default=False)),
                ('contest', models.BooleanField(default=False)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='managecycle.Cycles')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteStatus',
            fields=[
                ('approve', models.BooleanField(default=False)),
                ('contest', models.BooleanField(default=False)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='managecycle.Cycles')),
            ],
        ),
    ]
