# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycleporthole', '0007_auto_20180715_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteStatus',
            fields=[
                ('approve', models.BooleanField(default=False)),
                ('contest', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cycleporthole.Quotes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
