# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyclestatus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='postatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='invoicesstatus',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cycleporthole.Invoices'),
        ),
        migrations.AlterField(
            model_name='postatus',
            name='po',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cycleporthole.PurchaseOrder'),
        ),
    ]
