# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyclestatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesstatus',
            name='cycle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='invoice_status', serialize=False, to='managecycle.Cycles'),
        ),
        migrations.AlterField(
            model_name='postatus',
            name='cycle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='po_status', serialize=False, to='managecycle.Cycles'),
        ),
        migrations.AlterField(
            model_name='quotestatus',
            name='cycle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quote_status', serialize=False, to='managecycle.Cycles'),
        ),
    ]
