# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclestatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesstatus',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postatus',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotestatus',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
