# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyclestatus', '0002_auto_20180724_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesstatus',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='postatus',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='quotestatus',
            name='cancelled',
        ),
    ]
