# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managecycle', '0002_auto_20180728_1908'),
        ('cyclestatus', '0002_auto_20180728_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleStatus',
            fields=[
                ('approve_quote', models.BooleanField(default=False)),
                ('contest_quote', models.BooleanField(default=False)),
                ('approve_po', models.BooleanField(default=False)),
                ('contest_po', models.BooleanField(default=False)),
                ('approve_invoice', models.BooleanField(default=False)),
                ('contest_invoice', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quote_status', serialize=False, to='managecycle.Cycles')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoicesstatus',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='postatus',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='quotestatus',
            name='cycle',
        ),
        migrations.DeleteModel(
            name='InvoicesStatus',
        ),
        migrations.DeleteModel(
            name='POStatus',
        ),
        migrations.DeleteModel(
            name='QuoteStatus',
        ),
    ]
