# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclestatus', '0002_invoicesstatus_postatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesstatus',
            name='comment',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='postatus',
            name='comment',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='quotestatus',
            name='comment',
            field=models.TextField(default=False),
        ),
    ]
