# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclestatus', '0003_auto_20180718_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesstatus',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postatus',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quotestatus',
            name='comment',
            field=models.TextField(),
        ),
    ]
