# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclestatus', '0003_auto_20180728_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclestatus',
            name='approve_invoice',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cyclestatus',
            name='approve_po',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cyclestatus',
            name='approve_quote',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cyclestatus',
            name='cancelled',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cyclestatus',
            name='complete',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cyclestatus',
            name='contest_invoice',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cyclestatus',
            name='contest_po',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cyclestatus',
            name='contest_quote',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cyclestatus',
            name='pending',
            field=models.BooleanField(),
        ),
    ]
