# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyclestatus', '0006_auto_20180718_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicesstatus',
            old_name='invoices',
            new_name='invoice',
        ),
    ]
