# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0009_auto_20180715_1907'),
        ('cyclestatus', '0007_auto_20180718_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceUrgency',
            fields=[
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cycles.Cycles')),
            ],
        ),
        migrations.CreateModel(
            name='POUrgency',
            fields=[
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cycles.Cycles')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteUrgency',
            fields=[
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cycles.Cycles')),
            ],
        ),
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgent', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoicesstatus',
            name='urgent',
        ),
        migrations.RemoveField(
            model_name='postatus',
            name='urgent',
        ),
        migrations.RemoveField(
            model_name='quotestatus',
            name='urgent',
        ),
    ]
