# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyclestatus', '0008_auto_20180719_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Urgency',
        ),
    ]
