# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclestatus', '0009_delete_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceurgency',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pourgency',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoteurgency',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
