# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclestatus', '0010_auto_20180719_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesstatus',
            name='action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postatus',
            name='action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotestatus',
            name='action',
            field=models.BooleanField(default=False),
        ),
    ]
