# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyclestatus', '0012_auto_20180719_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceurgency',
            name='is_invoice',
        ),
        migrations.RemoveField(
            model_name='pourgency',
            name='is_po',
        ),
        migrations.RemoveField(
            model_name='quoteurgency',
            name='is_quote',
        ),
    ]
