# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyclestatus', '0014_auto_20180719_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceaction',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceurgency',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='poaction',
            name='po',
        ),
        migrations.RemoveField(
            model_name='pourgency',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='quoteaction',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quoteurgency',
            name='cycle',
        ),
        migrations.DeleteModel(
            name='InvoiceAction',
        ),
        migrations.DeleteModel(
            name='InvoiceUrgency',
        ),
        migrations.DeleteModel(
            name='POAction',
        ),
        migrations.DeleteModel(
            name='POUrgency',
        ),
        migrations.DeleteModel(
            name='QuoteAction',
        ),
        migrations.DeleteModel(
            name='QuoteUrgency',
        ),
    ]
