# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
