# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
    ]
