# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180710_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
