# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180725_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='is_client',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='is_member',
            field=models.NullBooleanField(),
        ),
    ]
