# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180710_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='is_client',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='is_member',
            field=models.BooleanField(),
        ),
    ]
