# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_alluser_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alluser',
            name='company',
        ),
    ]
