# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managejobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_cycle', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managejobs.Jobs')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_cycle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
