# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managecycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycles',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_cycle', to=settings.AUTH_USER_MODEL),
        ),
    ]
