# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycles',
            name='end_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cycles',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cycles',
            name='start_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
