# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managecycle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycles',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='cycles',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='cycles',
            name='payment_pending',
        ),
    ]
