# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 15:35
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('managecycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycles',
            name='cycle_value',
            field=djmoney.models.fields.MoneyField(decimal_places=1, default=Decimal('0'), default_currency='GBP', max_digits=11),
        ),
    ]
