# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecycle', '0002_auto_20180731_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycles',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
