# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecycle', '0002_auto_20180723_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycles',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
