# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecycle', '0003_cycles_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycles',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
