# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 16:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecycle', '0003_auto_20180729_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycles',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 16, 42, 52, 97455)),
        ),
    ]
