# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecycle', '0004_cycles_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycles',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 17, 47, 41, 700503)),
        ),
    ]
