# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecycle', '0005_auto_20180729_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycles',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
