# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managejobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
