# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managejobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='start_date',
        ),
    ]
